sonar.projectKey=DEFRA_lis-apps-cattle-move
sonar.organization=defra
sonar.qualitygate.ignoreSmallChanges=false

sonar.links.homepage=https://github.com/DEFRA/lis-apps-cattle-move
sonar.links.ci=https://github.com/DEFRA/lis-apps-cattle-move/actions
sonar.links.scm=https://github.com/DEFRA/lis-apps-cattle-move
sonar.links.issue=https://github.com/DEFRA/lis-apps-cattle-move/issues

sonar.sources=src
sonar.tests=src

sonar.exclusions=\
  src/**/*.test.js,\
  src/**/*.spec.js,\
  src/**/*.test.ts,\
  src/**/*.spec.ts,\
  src/**/*.test.jsx,\
  src/**/*.spec.jsx,\
  src/**/*.test.tsx,\
  src/**/*.spec.tsx

sonar.test.inclusions=\
  src/**/*.test.js,\
  src/**/*.spec.js,\
  src/**/*.test.ts,\
  src/**/*.spec.ts,\
  src/**/*.test.jsx,\
  src/**/*.spec.jsx,\
  src/**/*.test.tsx,\
  src/**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
