#file: noinspection UndefinedParamsPresent,UndefinedAction
name: 'Prerelease'

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'

concurrency:
  group: prerelease-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  get-version:
    name: 'Calculate Version'
    uses: ./.github/workflows/support-version.yml
    with:
      ref: ${{ github.sha }}
      branch: ${{ github.ref_name }}
      release-type: prerelease

  validate:
    name: 'Validate'
    needs: get-version
    uses: ./.github/workflows/support-validate.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.sha }}

  sonar-analysis:
    name: 'Sonar Analysis'
    needs: [get-version, validate]
    uses: ./.github/workflows/support-sonar.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.sha }}
      branch: ${{ github.ref_name }}
    secrets: inherit

  create-tag:
    name: 'Tag Validated Commit'
    needs: [get-version, validate, sonar-analysis]
    if: needs.sonar-analysis.outputs.quality-gate-status == 'PASSED'
    uses: ./.github/workflows/support-tag.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.sha }}
    secrets: inherit
