#file: noinspection UndefinedParamsPresent,UndefinedAction
name: 'Release'

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  group: main-release
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  get-version:
    name: 'Calculate Stable Version'
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/support-version.yml
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
      branch: ${{ github.event.pull_request.head.ref }}
      release-type: stable

  validate:
    name: 'Validate Merged Commit'
    needs: get-version
    uses: ./.github/workflows/support-validate.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.event.pull_request.merge_commit_sha }}

  sonar-analysis:
    name: 'Sonar Analysis'
    needs: [get-version, validate]
    uses: ./.github/workflows/support-sonar.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.event.pull_request.merge_commit_sha }}
      branch: main
    secrets: inherit

  create-tag:
    name: 'Tag Main'
    needs: [get-version, validate, sonar-analysis]
    if: needs.sonar-analysis.outputs.quality-gate-status == 'PASSED'
    uses: ./.github/workflows/support-tag.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.event.pull_request.merge_commit_sha }}
    secrets: inherit
